dotenv: .env
networks:
  default: development
  rinkeby:
    verify: True
  mainnet-fork:
    verify: True
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}